name: Reuseable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: result of reuseable workflow
        value: $ {{ jobs.deploy.outputs.outcome }}
    #secrets:
    #  some-secret:
    #    required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
      #- name: Output result in reuseable
      #  run: |
      #   echo "${{ outputs.step-result }}"
      #   echo "${{ steps.set-result.outputs.setp-result }}"